services:
  - type: web
    name: atsede-library
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"
      - key: GITHUB_REPO
        value: shetesfa/atsede_library
      - key: GITHUB_BRANCH
        value: main
      - key: GITHUB_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
